### ISSUE TITLE
Potential Bug: color of lemonbar-xft seems different when changing from top to bottom position!

### ISSUE THREAD

**Issue by Joe23232** [domsson/succade#38]
![image](https://user-images.githubusercontent.com/34926497/86728300-ad52a980-c06f-11ea-84d1-0e063ce965e2.png)

As you can see the `lemonbar-xft`'s color bar seems to be different when changing from top to bottom.

Background color is set to `background = "#2a2c41"`. When changing it to bottom it seems to turn more purplish. Is the default config file for succade set to have transparency?

**Comment by domsson** [comment]
I took the image into GIMP and checked the color codes of the top and bottom bar - they are both `#2a2c41`. This is just one of those optical illusion kind of things, where the bottom bar looks a different tone because the wallpaper is darker at the bottom vs. at the top.

**Comment by Joe23232** [comment]
@domsson My bad I didn't realise :) is there transparency being used by default?

**Comment by domsson** [comment]
No, transparency is not used unless you specify it in the color (#aarrggbb).
