### ISSUE TITLE
May I please retrieve an example version of succade?

### ISSUE THREAD

**Issue by Joe23232** [domsson/succade#48]
Hey man how is it going @domsson ? I was just wondering if you had an example version of `succade` setup config file that I could use.

I am going to again attempt to write the program that I wanted which deals with workspaces but this time in a language called V rather than Rust (it honestly got way to complicated).

**Comment by domsson** [comment]
Hey Joe,

there are two example config files in the `cfg` directory. Those should get you started. You can test them by using the `-c` command line flag, like for example so (assuming your current working directory is the succade directory):

    ./bin/succade -c ./cfg/example1.ini

The documentation in the README explains all possible config options. If there are any things I forgot to explain or didn't explain properly or if you have any specific questions regarding configuration in general, let me know here.

Also, note that from version 2 on, the config syntax has changed somewhat. So if you have an older config lying around but are using the newest version of succade, you will most likely have to adapt it somewhat. You can always check your version of succade via the `-V` command line switch:

    ./bin/succade -V

**Comment by Joe23232** [comment]
Hey @domsson I know this is completely off topic but does `lemonbar` support wayland?

**Comment by domsson** [comment]
No, Lemonbar has been written for X. If you look at the source code, you'll see several [xcb](https://en.wikipedia.org/wiki/XCB) libraries being included, which is a X11 client library. If you're looking for a cool project, porting Lemonbar to Wayland would be appreciated by many, I'm sure. :)

**Comment by Joe23232** [comment]
Cool mate, thanks anyways =D
