### ISSUE TITLE
Separator config option

### ISSUE THREAD

**Issue by jasper-schnabel** [domsson/succade#49]
It would be nice if you could have the option to set an overall separator for the blocks.

For example:
```
[bar]
separator = "|"
```
Output: 

date | cpu | memory | battery

**Comment by domsson** [comment]
This can already be achieved by using `prefix` and `suffix` on the appropriate blocks, but that's pretty cumbersome. The `separator` option would make this much more convenient. Therefore, nice idea, I'll put it on my to-do list.

**Comment by domsson** [comment]
I was actually a bit hesitant to add this, for two reasons:

- as mentioned, it can already be achieved via `prefix` and `suffix`, and I try to keep the code simple
- once the `separator` option is available, someone would probably want `separator-foreground` and `separator-background` options as well, but that would add a bit too much code for my taste.

However, implementing just `separator` was pretty easy and only cost a couple lines of code, so I decided to go ahead and do it anyway. Let me know if it works as expected. :)

**Comment by jasper-schnabel** [comment]
It works exactly the way I wanted it to work. 
Thanks
