### ISSUE TITLE
Two bars

### ISSUE THREAD

**Issue by BeyondMagic** [domsson/succade#52]
Is there any way of loading two bars right now? I wanted one at the bottom and other at the top.

**Comment by domsson** [comment]
That should be possible:

 - Make two config files, one for the top bar, the other for the bottom bar
 - Start two instances of succade with the `-c` command line argument, specifying the appropriate config to use for each

Let me know if that works. :)

**Comment by BeyondMagic** [comment]
Oh, thanks, I'll try it! Yep, it works.
