### ISSUE TITLE
Double percentage

### ISSUE THREAD

**Issue by BeyondMagic** [domsson/succade#53]
The following config outputs two percentage characters (**%%**). How can I avoid that?

```lua
[bar]
name = "testbar"
blocks = "desktop"
width = 1440
height = 19
font = 'Noto Sans CJK JP:size=11:antialias=true'
affix-font = "Powerline Extra Symbols:antialias=true:size=10"


[desktop]
command = "echo %"
```

**Comment by domsson** [comment]
Hm, it outputs only one for me (succade 2.1.3). Could you run `succade -V` and let me know what version you are on?

**Comment by BeyondMagic** [comment]
2.1.3 as well, then... it's a problem with my lemonbar? I'm using [lemonbar-xft](https://github.com/drscream/lemonbar-xft) to load fontconfig.

![image](https://user-images.githubusercontent.com/51831435/109200731-b8358800-777f-11eb-96bd-cf0617bd0bd1.png)

**Comment by domsson** [comment]
Hm, not quite sure. Interested to figure it out, though! Could you try the following and see if it changes anything?

- Create a simple bash script with just the `echo %`
- Save it somewhere in your path, let's say `.local/bin/test-script` (assuming `./local/bin` is in your path)
- Change the config to `command = test-script`

**Comment by BeyondMagic** [comment]
Thanks for responding! the problem remains. I named the script to `bar` and did `chmod +x` on it to be sure that it loads. I did change the `succaderc` to `command = bar` and it stills loading two bars.
![image](https://user-images.githubusercontent.com/51831435/109351886-bee3fe00-7858-11eb-973a-0dc6b97dc90b.png)

**Comment by BeyondMagic** [comment]
Yep, so tried with a few things, it looks like `lemonbar-xft` (AUR latest version) with support for fontconfig prints out two percentage, while the normal `lemonbar` prints out only one with succade.

However, using `lemonbar-xft` and a normal script, it prints out normally. It seems that `succade` hasn't full compatibility with `lemonbar-xft`.

**Comment by BeyondMagic** [comment]
Fixed with the following [fork](https://github.com/expectocode/bar) with support of `fontconfig`, although `lemonbar-xft` indeeed hasn't full support of `succade`.

Thank for the amazing program, @domsson.
