### ISSUE TITLE
Hi, how would I connect an external script to it?

### ISSUE THREAD

**Issue by Joe23232** [domsson/succade#54]
Hey man I don't know if you remember me. it has been a while since I have tried any of this and this is because I have been away.

Anyways I wanted to try this again but I forgot how do I connect a script to your code?

Here is my current succade config file (very similar to your default configuration).

```
[bar]
name = "testbar"
blocks = "desktop | user | date time"
height = 24
areas = 16
foreground = "#222222"
background = "#262626"
line-color = "#555555"
line-width = 2
bottom = true

[default]
label-foreground = "#dddddd"
affix-foreground = "#555555"
margin = 8
padding-left = 1
prefix = "[ " 
suffix = " ]"
underline = true

[desktop]
command = "bspc query -D -d focused --names"
trigger = "bspc subscribe"
label = "WORKSPACE"
margin-left = 8

[user]
command = "whoami"
label = "USER"

[date]
command = "date +'%Y-%m-%d'"
interval = 1
label = "DATE"

[time]
command = "date +'%H:%M:%S'"
interval = 1
label = "TIME"
mouse-left = "xclock"
margin-right = 8
```

I wanted to connect my script that will show on the left hand side:

![image](https://user-images.githubusercontent.com/34926497/112720971-90d80380-8f55-11eb-97b4-b9e551e092eb.png)

**Comment by domsson** [comment]
Hey Joe, not sure what you mean when you say you want to "connect" your script. But as long as your script outputs text, you can simply use it as the `command`. Say your script is called `joe-foo-bar`, then in your config, have something like:

    [foo-bar]
    command = "joe-foo-bar"
    
This assumes the script is in your `PATH`.

**Comment by Joe23232** [comment]
Hey man,

Oh I see, thanks mate :)

**Comment by domsson** [comment]
Assuming this is solved. Otherwise let me know.
